name: Publish to pub.dev

on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: .
